import type { TarotCard } from './types';

const majorArcana: TarotCard[] = [
  {
    id: 'major-00-fool',
    number: 0,
    arcana: 'major',
    nameZh: '愚者',
    nameEn: 'The Fool',
    image: new URL('../../tarot_img/00.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['新开始', '自由', '信任', '冒险'],
        general: '新的旅程正在展开，带着好奇心出发会遇见意外的可能。',
        love: '感情适合放下预设，以轻松真诚的方式认识彼此。',
        career: '大胆尝试新方向，但要在行动前确认基本风险。',
        wealth: '财务处于探索期，小额尝试比孤注一掷更合适。',
        growth: '学习信任生命，同时为自己的选择承担责任。',
      },
      reversed: {
        keywords: ['鲁莽', '迟疑', '逃避', '准备不足'],
        general: '冲动或过度犹豫都可能让机会偏离，需要先看清后果。',
        love: '关系里可能害怕承诺或只顾新鲜感，宜坦白真实期待。',
        career: '未经准备的转向容易返工，先补足信息与能力缺口。',
        wealth: '警惕随性消费和高风险下注，暂缓无法解释的投资。',
        growth: '辨认自由与逃避的差别，让勇气建立在觉察之上。',
      },
    },
  },
  {
    id: 'major-01-magician',
    number: 1,
    arcana: 'major',
    nameZh: '魔术师',
    nameEn: 'The Magician',
    image: new URL('../../tarot_img/01.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['创造', '专注', '资源', '行动'],
        general: '你已具备所需工具，集中意志就能把想法带入现实。',
        love: '主动而清晰的表达能点燃吸引力并推进关系。',
        career: '善用沟通与专业能力，适合启动项目或争取机会。',
        wealth: '凭技能创造收入的窗口打开，规划后即可付诸行动。',
        growth: '把注意力收回当下，认识自己拥有的真实力量。',
      },
      reversed: {
        keywords: ['操控', '分心', '才能受阻', '空谈'],
        general: '资源没有被诚实或有效地使用，表象可能大于实质。',
        love: '甜言蜜语或控制欲会损害信任，需要核对言行是否一致。',
        career: '目标分散或能力被误用，先停止包装并完成关键任务。',
        wealth: '提防夸大收益的方案，也别因自信过头忽略成本。',
        growth: '承认自己的动机与阴影，才能把天赋导向正途。',
      },
    },
  },
  {
    id: 'major-02-high-priestess',
    number: 2,
    arcana: 'major',
    nameZh: '女祭司',
    nameEn: 'The High Priestess',
    image: new URL('../../tarot_img/02.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['直觉', '静默', '潜意识', '神秘'],
        general: '答案尚未完全显现，安静观察比急于定论更有价值。',
        love: '细微感受胜过表面承诺，给关系留出真实靠近的空间。',
        career: '先收集隐性信息并相信专业直觉，不必过早公开计划。',
        wealth: '财务决定需要耐心研究，暂时保守有助于看清全貌。',
        growth: '通过独处、梦境或书写倾听内在深处的声音。',
      },
      reversed: {
        keywords: ['忽视直觉', '秘密', '封闭', '信息混乱'],
        general: '内在声音被噪音盖住，隐瞒或误读正在制造不安。',
        love: '不说出口的情绪形成距离，猜测无法替代诚实交流。',
        career: '办公室暗流或信息不全影响判断，应核实而非凭传闻。',
        wealth: '看不懂的条款可能藏有代价，先暂停并寻求可靠意见。',
        growth: '停止向外索要所有答案，重新建立对感受的辨识力。',
      },
    },
  },
  {
    id: 'major-03-empress',
    number: 3,
    arcana: 'major',
    nameZh: '皇后',
    nameEn: 'The Empress',
    image: new URL('../../tarot_img/03.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['丰盛', '滋养', '创造力', '感官'],
        general: '耐心照料正在让事物成熟，丰盛来自持续的给予与接纳。',
        love: '关系充满温柔与吸引力，适合表达关怀并共建安全感。',
        career: '创意与协作能结出成果，也适合培育长期项目。',
        wealth: '稳定资源逐渐累积，可为品质生活做有节制的投入。',
        growth: '善待身体与情绪，允许自己接收支持和快乐。',
      },
      reversed: {
        keywords: ['过度付出', '匮乏感', '创意停滞', '忽略自己'],
        general: '照顾别人过多或内在匮乏，正消耗原本的生命力。',
        love: '依赖、窒息式关怀或自我忽视使关系失去平衡。',
        career: '灵感被疲惫压住，先恢复边界再要求持续产出。',
        wealth: '用消费填补情绪难有满足，应分清需要与补偿。',
        growth: '把滋养先还给自己，不必用牺牲证明价值。',
      },
    },
  },
  {
    id: 'major-04-emperor',
    number: 4,
    arcana: 'major',
    nameZh: '皇帝',
    nameEn: 'The Emperor',
    image: new URL('../../tarot_img/04.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['秩序', '责任', '领导', '稳定'],
        general: '建立结构与规则能稳住局面，成熟的权威来自担当。',
        love: '可靠承诺与清楚边界让关系更有安全感。',
        career: '适合制定制度、承担管理责任并执行长期计划。',
        wealth: '纪律化预算与稳健配置能够巩固财务基础。',
        growth: '练习自律和决定力，同时学会保护而非控制。',
      },
      reversed: {
        keywords: ['控制', '僵化', '权威冲突', '失序'],
        general: '过度掌控或缺乏纪律都在削弱稳定，需要调整权力方式。',
        love: '强势规则压缩了亲密空间，应以协商替代命令。',
        career: '僵硬管理或责任不清造成阻力，重新界定权限与目标。',
        wealth: '财务控制失衡，可能过度紧缩或毫无规划。',
        growth: '看见对失控的恐惧，培养有弹性的内在秩序。',
      },
    },
  },
  {
    id: 'major-05-hierophant',
    number: 5,
    arcana: 'major',
    nameZh: '教皇',
    nameEn: 'The Hierophant',
    image: new URL('../../tarot_img/05.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['传统', '学习', '信念', '导师'],
        general: '成熟传统或可信导师能提供方向，先理解规则再创新。',
        love: '共同价值观与正式承诺成为关系的重要基础。',
        career: '遵循专业规范并向有经验者学习，会获得认可。',
        wealth: '采用经过验证的财务方法，避免不熟悉的投机。',
        growth: '整理自己的信念体系，从传承中找到稳定支点。',
      },
      reversed: {
        keywords: ['教条', '反叛', '价值冲突', '独立思考'],
        general: '旧规则已不完全适用，需要分辨传统与教条。',
        love: '外界标准或价值差异让关系承压，应定义自己的承诺。',
        career: '体制限制创造力，可在理解代价后寻找新路径。',
        wealth: '盲从所谓权威可能误导判断，务必独立核实建议。',
        growth: '质疑继承来的观念，建立亲身验证过的信念。',
      },
    },
  },
  {
    id: 'major-06-lovers',
    number: 6,
    arcana: 'major',
    nameZh: '恋人',
    nameEn: 'The Lovers',
    image: new URL('../../tarot_img/06.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['结合', '选择', '价值一致', '亲密'],
        general: '重要选择需要忠于核心价值，真诚联结会带来整合。',
        love: '双方吸引且愿意坦诚选择彼此，关系有深化机会。',
        career: '价值相合的合作能发挥优势，重大决定要听从初心。',
        wealth: '与伴侣或伙伴公开财务观念，有助于做出共同选择。',
        growth: '接纳内在不同面向，以一致的价值指导行动。',
      },
      reversed: {
        keywords: ['失衡', '诱惑', '选择困难', '关系裂痕'],
        general: '言行与价值不一致，回避选择只会延长冲突。',
        love: '沟通断裂或承诺摇摆，需要正视不对等与真实需求。',
        career: '合作价值观不合，仓促结盟可能带来长期摩擦。',
        wealth: '共同财务缺乏共识，避免因取悦他人承担不合理开支。',
        growth: '停止把决定交给外界，承担选择及其后果。',
      },
    },
  },
  {
    id: 'major-07-chariot',
    number: 7,
    arcana: 'major',
    nameZh: '战车',
    nameEn: 'The Chariot',
    image: new URL('../../tarot_img/07.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['意志', '推进', '胜利', '自我掌控'],
        general: '相反力量被统一到明确目标上，坚定推进可突破阻碍。',
        love: '双方明确方向并愿意行动，关系能够快速向前。',
        career: '竞争中保持专注与纪律，有望赢得关键进展。',
        wealth: '设定清晰财务目标并持续执行，会看到可量化成果。',
        growth: '驾驭情绪而非压抑情绪，让意志服务真正方向。',
      },
      reversed: {
        keywords: ['失控', '方向混乱', '强行推进', '挫败'],
        general: '力量彼此拉扯，硬冲只会放大偏差，宜先校准方向。',
        love: '关系节奏不一或争夺主导权，暂缓推进并重新协商。',
        career: '目标模糊导致忙而无功，也要避免把同事当成对手。',
        wealth: '冲动追逐结果容易超支，先重整预算与优先级。',
        growth: '承认无法控制一切，把精力放在可选择的行动上。',
      },
    },
  },
  {
    id: 'major-08-strength',
    number: 8,
    arcana: 'major',
    nameZh: '力量',
    nameEn: 'Strength',
    image: new URL('../../tarot_img/08.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['勇气', '耐心', '慈悲', '内在力量'],
        general: '温柔而坚定的力量足以化解紧张，不必用强硬证明自己。',
        love: '耐心接纳彼此脆弱，亲密会在安全中加深。',
        career: '面对压力保持沉着，以韧性和同理心赢得信任。',
        wealth: '克制即时欲望，稳定习惯比激进策略更有效。',
        growth: '拥抱本能与情绪，用慈悲将它们转化为勇气。',
      },
      reversed: {
        keywords: ['自我怀疑', '压抑', '失去耐心', '虚弱'],
        general: '内在不安正在削弱信心，逞强或退缩都不是答案。',
        love: '缺乏安全感可能变成讨好或嫉妒，需要先安顿自己。',
        career: '压力触发自我否定，缩小目标并重建可见的进步。',
        wealth: '情绪性消费或害怕行动都源于不安，先恢复掌控感。',
        growth: '允许脆弱存在，真正的力量不要求永远坚强。',
      },
    },
  },
  {
    id: 'major-09-hermit',
    number: 9,
    arcana: 'major',
    nameZh: '隐者',
    nameEn: 'The Hermit',
    image: new URL('../../tarot_img/09.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['独处', '内省', '智慧', '寻找'],
        general: '暂离喧嚣有助于看清方向，答案来自诚实的内在探索。',
        love: '需要个人空间理解情感，成熟关系能尊重这段沉淀。',
        career: '适合深度研究、独立工作或向真正的专家请教。',
        wealth: '减少外界比较，审视长期需求后再安排资源。',
        growth: '用独处照亮内心，也把所得智慧带回现实。',
      },
      reversed: {
        keywords: ['孤立', '逃避', '封闭', '迷失'],
        general: '独处已变成隔绝，反复思索却没有带来新的视角。',
        love: '害怕受伤而关闭沟通，会让双方越来越难以靠近。',
        career: '独自承担过久形成盲点，应主动寻求反馈与支持。',
        wealth: '因焦虑回避账目只会加重压力，需要面对真实数字。',
        growth: '适时走出洞穴，让可信关系帮助你校正内在判断。',
      },
    },
  },
  {
    id: 'major-10-wheel-of-fortune',
    number: 10,
    arcana: 'major',
    nameZh: '命运之轮',
    nameEn: 'Wheel of Fortune',
    image: new URL('../../tarot_img/10.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['转机', '周期', '机缘', '变化'],
        general: '局势进入新的周期，顺应变化能抓住意外转机。',
        love: '关系阶段正在转换，开放面对会带来新的相处方式。',
        career: '时机开始转好，准备充分的人更能接住突发机会。',
        wealth: '财运有所流动，可把好运转化为稳健的长期安排。',
        growth: '理解无常并参与变化，不把命运误解为被动等待。',
      },
      reversed: {
        keywords: ['阻滞', '坏时机', '重复模式', '抗拒变化'],
        general: '外部变化暂不顺利，旧模式也可能再次出现。',
        love: '关系卡在循环冲突中，需要改变熟悉却无效的反应。',
        career: '计划受时机影响延迟，保留弹性而非责怪运气。',
        wealth: '波动加大，避免追涨并预留应急空间。',
        growth: '辨认自己能改变的部分，在不确定中练习稳定。',
      },
    },
  },
  {
    id: 'major-11-justice',
    number: 11,
    arcana: 'major',
    nameZh: '正义',
    nameEn: 'Justice',
    image: new URL('../../tarot_img/11.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['公平', '真相', '因果', '责任'],
        general: '事实与责任需要被正视，公正判断会带来清晰结果。',
        love: '坦诚讨论彼此责任与边界，关系才能保持平等。',
        career: '客观证据和专业伦理是决定成败的关键。',
        wealth: '核对合同、税务与账目，透明管理能够避免后患。',
        growth: '承担行为后果，并以一致标准要求自己。',
      },
      reversed: {
        keywords: ['不公', '偏见', '逃责', '失衡'],
        general: '事实可能被扭曲或责任遭到推卸，应重新核查依据。',
        love: '双重标准和积怨破坏平衡，需要诚实承认各自影响。',
        career: '不透明流程或偏见带来挫折，保存证据并寻求正式渠道。',
        wealth: '合同疏漏或错误账目可能造成损失，及时纠正。',
        growth: '停止合理化自己的选择，用诚实恢复内在平衡。',
      },
    },
  },
  {
    id: 'major-12-hanged-man',
    number: 12,
    arcana: 'major',
    nameZh: '倒吊人',
    nameEn: 'The Hanged Man',
    image: new URL('../../tarot_img/12.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['暂停', '换位', '臣服', '新视角'],
        general: '主动暂停能换来不同视角，暂时放手不是失败。',
        love: '关系需要放慢并理解对方立场，旧期待可被重新定义。',
        career: '项目暂缓适合复盘，不宜用更多力气重复旧方法。',
        wealth: '推迟非必要支出，从长期角度重新评估价值。',
        growth: '放下控制欲，允许空白孕育新的理解。',
      },
      reversed: {
        keywords: ['拖延', '徒劳牺牲', '停滞', '抗拒'],
        general: '无止境等待已失去意义，牺牲没有换来真正改变。',
        love: '单方面迁就造成委屈，应决定继续投入还是重新设限。',
        career: '以等待掩饰害怕决定，需明确下一步和截止点。',
        wealth: '资金长期卡住却不复盘，及时止损比继续僵持更重要。',
        growth: '辨别臣服与自我放弃，恢复主动选择的能力。',
      },
    },
  },
  {
    id: 'major-13-death',
    number: 13,
    arcana: 'major',
    nameZh: '死神',
    nameEn: 'Death',
    image: new URL('../../tarot_img/13.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['结束', '转化', '告别', '重生'],
        general: '一个阶段必须结束，腾出的空间会承载真正的新生。',
        love: '旧的关系模式走到尽头，诚实告别或彻底更新成为主题。',
        career: '职业结构出现根本转变，放下过时身份才能前进。',
        wealth: '终止无效支出与旧财务习惯，重建更健康的系统。',
        growth: '允许哀伤完成它的过程，从放下中获得更新。',
      },
      reversed: {
        keywords: ['抗拒结束', '停滞', '恐惧改变', '旧事纠缠'],
        general: '紧抓已结束的事物，使必要转化迟迟无法发生。',
        love: '害怕失去让关系困在旧伤中，需要面对真实变化。',
        career: '明知方向不再适合却不愿调整，拖延会增加代价。',
        wealth: '不肯停止亏损或坏习惯，财务复原因而受阻。',
        growth: '温柔承认恐惧，并从一个可承受的告别开始。',
      },
    },
  },
  {
    id: 'major-14-temperance',
    number: 14,
    arcana: 'major',
    nameZh: '节制',
    nameEn: 'Temperance',
    image: new URL('../../tarot_img/14.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['平衡', '调和', '耐心', '疗愈'],
        general: '不同元素正在找到合适比例，温和调整胜过极端行动。',
        love: '耐心沟通与互相迁就让关系恢复和谐。',
        career: '整合团队优势并稳定节奏，长期成果会自然累积。',
        wealth: '收支保持适度，循序渐进的配置最为有利。',
        growth: '接纳内在矛盾，在中道中完成持续疗愈。',
      },
      reversed: {
        keywords: ['失衡', '过度', '急躁', '不协调'],
        general: '生活比例失调，急于求成正让问题变得更复杂。',
        love: '双方节奏与需求难以调和，情绪过量需要先降温。',
        career: '任务分配混乱或合作失配，应删减并重新排序。',
        wealth: '过度消费或极端节省都不可持续，需要恢复适度。',
        growth: '观察自己在哪个领域走向极端，再做小幅修正。',
      },
    },
  },
  {
    id: 'major-15-devil',
    number: 15,
    arcana: 'major',
    nameZh: '恶魔',
    nameEn: 'The Devil',
    image: new URL('../../tarot_img/15.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['束缚', '欲望', '成瘾', '阴影'],
        general: '欲望或恐惧形成看似牢固的锁链，诚实看见才有选择。',
        love: '强烈吸引可能混合依赖、占有或不健康的权力关系。',
        career: '金钱地位的诱惑让人困在消耗性环境，应评估代价。',
        wealth: '债务、赌博或物质执着需要被直接管理。',
        growth: '承认被压抑的欲望，不让羞耻继续暗中支配。',
      },
      reversed: {
        keywords: ['解脱', '觉醒', '打破依赖', '重获选择'],
        general: '你开始看清束缚并愿意松开，改变已经有了入口。',
        love: '识别有害依附后，关系可重设边界或走向结束。',
        career: '逐步退出消耗与控制，重新选择符合价值的道路。',
        wealth: '主动处理债务与成瘾性消费，财务自由开始恢复。',
        growth: '把阴影带入意识，以具体行动结束旧循环。',
      },
    },
  },
  {
    id: 'major-16-tower',
    number: 16,
    arcana: 'major',
    nameZh: '高塔',
    nameEn: 'The Tower',
    image: new URL('../../tarot_img/16.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['突变', '崩塌', '真相揭露', '释放'],
        general: '不稳固的结构突然瓦解，震动同时释放被压住的真相。',
        love: '隐瞒或脆弱基础被揭开，关系必须面对根本问题。',
        career: '组织或计划突发变化，先确保安全再快速重整。',
        wealth: '意外支出或市场震荡提醒你建立更强缓冲。',
        growth: '让虚假认同倒下，从真实废墟上重新开始。',
      },
      reversed: {
        keywords: ['避免灾变', '内在震荡', '延迟崩塌', '抗拒真相'],
        general: '危机可能暂被压住，但逃避必要改变会累积压力。',
        love: '双方绕开核心裂缝，表面和平难以长久维持。',
        career: '已察觉风险却不愿调整，应在被迫中断前行动。',
        wealth: '财务警讯尚可控制，立即减少暴露并准备预案。',
        growth: '承认内心正在重组，主动拆除不再真实的部分。',
      },
    },
  },
  {
    id: 'major-17-star',
    number: 17,
    arcana: 'major',
    nameZh: '星星',
    nameEn: 'The Star',
    image: new URL('../../tarot_img/17.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['希望', '疗愈', '灵感', '真诚'],
        general: '经历风暴后希望重新出现，诚实做自己会恢复流动。',
        love: '关系有温柔修复的可能，单身者也更愿意相信爱。',
        career: '愿景与创造力被重新点亮，长期方向逐渐清楚。',
        wealth: '财务慢慢复原，保持信心同时继续务实规划。',
        growth: '以真实和开放滋养自己，让希望成为稳定实践。',
      },
      reversed: {
        keywords: ['失望', '信心不足', '灵感枯竭', '自我怀疑'],
        general: '暂时看不见希望不等于没有出路，疲惫需要被照顾。',
        love: '旧伤让人难以信任亲密，避免用悲观预判结局。',
        career: '对方向失去信心，可回到最初价值寻找微小亮点。',
        wealth: '复原速度慢于预期，不宜因此放弃基本计划。',
        growth: '停止要求立刻乐观，从接纳当下开始恢复信念。',
      },
    },
  },
  {
    id: 'major-18-moon',
    number: 18,
    arcana: 'major',
    nameZh: '月亮',
    nameEn: 'The Moon',
    image: new URL('../../tarot_img/18.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['迷雾', '潜意识', '不安', '想象'],
        general: '信息仍在迷雾中，情绪与想象可能放大未知。',
        love: '关系中有未说清的感受，慢慢核实而非自行补完故事。',
        career: '局势不透明，不适合仅凭表象做不可逆决定。',
        wealth: '隐藏费用或市场不确定性增加，应保守并查清细节。',
        growth: '倾听梦境与恐惧传递的信息，但不把感受当成事实。',
      },
      reversed: {
        keywords: ['迷雾消散', '真相浮现', '焦虑缓解', '自欺'],
        general: '混乱开始退去，或自我欺骗正被迫显露。',
        love: '误会有机会澄清，前提是愿意面对不舒服的事实。',
        career: '隐藏信息逐渐出现，可据新证据修正判断。',
        wealth: '账目真相变得清楚，及时处理曾被忽略的问题。',
        growth: '识别焦虑制造的幻象，练习把直觉与投射分开。',
      },
    },
  },
  {
    id: 'major-19-sun',
    number: 19,
    arcana: 'major',
    nameZh: '太阳',
    nameEn: 'The Sun',
    image: new URL('../../tarot_img/19.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['喜悦', '成功', '活力', '清晰'],
        general: '光明照亮局势，真诚与生命力带来可分享的成功。',
        love: '关系温暖坦荡，适合庆祝承诺与共同生活的快乐。',
        career: '成果被看见，自信表达能获得认可与支持。',
        wealth: '财务趋势积极，可享受成果并继续为未来储备。',
        growth: '允许自己被看见，以单纯喜悦连接真实自我。',
      },
      reversed: {
        keywords: ['短暂阴霾', '过度乐观', '快乐受阻', '自负'],
        general: '好结果仍可能到来，但期待过高或细节疏忽遮住光亮。',
        love: '表面快乐下有未处理需求，应放下理想化并真实相处。',
        career: '成绩被延迟或自信变成自负，重新校准表达方式。',
        wealth: '乐观消费可能削弱成果，享受之余仍需量入为出。',
        growth: '不必强迫自己积极，接纳阴影会让快乐更真实。',
      },
    },
  },
  {
    id: 'major-20-judgement',
    number: 20,
    arcana: 'major',
    nameZh: '审判',
    nameEn: 'Judgement',
    image: new URL('../../tarot_img/20.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['觉醒', '召唤', '复盘', '重生'],
        general: '过去经验汇聚成清晰召唤，现在适合做出诚实决定。',
        love: '旧问题被重新审视，关系可在原谅与责任中重生。',
        career: '职业使命变得明确，复盘成果后迎接更大责任。',
        wealth: '全面检视财务历史，成熟选择能开启新的阶段。',
        growth: '原谅曾经的自己，并回应内心真正的召唤。',
      },
      reversed: {
        keywords: ['自我批判', '逃避召唤', '迟疑', '旧账未清'],
        general: '害怕被评价或无法原谅自己，使重要决定停滞。',
        love: '旧错反复被审判却未真正处理，需要放下指责循环。',
        career: '忽视内在召唤会加深空虚，别让完美主义阻止转向。',
        wealth: '过去财务错误仍影响选择，应面对而非羞耻逃避。',
        growth: '把反省从惩罚变成学习，给自己重新选择的机会。',
      },
    },
  },
  {
    id: 'major-21-world',
    number: 21,
    arcana: 'major',
    nameZh: '世界',
    nameEn: 'The World',
    image: new URL('../../tarot_img/21.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['完成', '整合', '圆满', '拓展'],
        general: '一个完整周期圆满收束，经验已经整合为新的起点。',
        love: '关系达到成熟阶段，适合共同庆祝或迈入长期承诺。',
        career: '重要项目完成并获得认可，更广阔舞台正在开启。',
        wealth: '长期努力形成稳定成果，可规划下一轮目标。',
        growth: '接纳旅程的全部经验，带着完整感走向新世界。',
      },
      reversed: {
        keywords: ['未完成', '延迟', '缺乏收尾', '停在门槛'],
        general: '最后一步尚未完成，遗漏细节让周期无法真正结束。',
        love: '关系卡在承诺门槛或旧事未结，需要明确闭环。',
        career: '项目接近完成却反复拖延，应集中处理收尾事项。',
        wealth: '目标差一点达成，避免此时松懈或过早庆祝。',
        growth: '找出尚未整合的经验，为结束赋予清楚意义。',
      },
    },
  },
];

const wands: TarotCard[] = [
  {
    id: 'wands-ace',
    number: 1,
    arcana: 'minor',
    suit: 'wands',
    rank: 'ace',
    nameZh: '权杖王牌',
    nameEn: 'Ace of Wands',
    image: new URL('../../tarot_img/Wands_Ace.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['灵感', '热情', '新行动'],
        general: '一股鲜明热情正在萌发，适合抓住火花并开始行动。',
        love: '新的吸引力被点燃，主动表达会让关系升温。',
        career: '创意项目或新机会出现，先做出可见的第一步。',
        wealth: '新收入想法值得小规模试行，但尚需持续投入。',
        growth: '跟随让你有生命力的方向，用行动回应内在召唤。',
      },
      reversed: {
        keywords: ['动力受阻', '延迟', '热情消退'],
        general: '灵感存在却难以落地，可能是方向不清或能量不足。',
        love: '吸引力忽冷忽热，避免用短暂激情代替真实了解。',
        career: '项目开局迟滞，先拆解障碍而不是强迫自己兴奋。',
        wealth: '新财路缺少成熟条件，不宜急着投入大笔资金。',
        growth: '找回真正想做的事，并允许自己从小处重新点火。',
      },
    },
  },
  {
    id: 'wands-two',
    number: 2,
    arcana: 'minor',
    suit: 'wands',
    rank: 'two',
    nameZh: '权杖二',
    nameEn: 'Two of Wands',
    image: new URL('../../tarot_img/Wands_Two.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['规划', '远见', '选择'],
        general: '视野已经打开，下一步需要在安全与拓展之间做决定。',
        love: '双方开始讨论未来方向，诚实规划能确认是否同行。',
        career: '适合制定扩张策略、研究市场或选择新的职业路径。',
        wealth: '先比较长期方案，再决定资源投向与风险边界。',
        growth: '把愿景变成路线图，主动走出熟悉范围。',
      },
      reversed: {
        keywords: ['畏缩', '计划不足', '选择受限'],
        general: '害怕未知让你停在原地，计划也可能缺少现实细节。',
        love: '对未来避而不谈，使关系难以确认共同方向。',
        career: '机会因犹豫或准备不周而缩小，需要重新评估能力。',
        wealth: '只看短期安全会错过布局，但贸然扩张同样危险。',
        growth: '辨认恐惧的具体内容，用可控尝试建立信心。',
      },
    },
  },
  {
    id: 'wands-three',
    number: 3,
    arcana: 'minor',
    suit: 'wands',
    rank: 'three',
    nameZh: '权杖三',
    nameEn: 'Three of Wands',
    image: new URL('../../tarot_img/Wands_Three.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['扩展', '远行', '成果初现'],
        general: '早期努力开始回响，适合拓展边界并等待更大成果。',
        love: '关系愿景逐渐成形，异地或共同旅行也可能成为主题。',
        career: '合作与外部市场带来成长，继续以长期眼光推进。',
        wealth: '先前布局开始产生回报，可谨慎扩大有效渠道。',
        growth: '相信积累的力量，把目光放到更宽广的世界。',
      },
      reversed: {
        keywords: ['进展延误', '视野受限', '合作受阻'],
        general: '期待的进展没有如期到来，需要检查规划与外部条件。',
        love: '距离或未来分歧让关系停滞，不能只靠等待解决。',
        career: '拓展计划遭遇物流、沟通或伙伴问题，应回到基础。',
        wealth: '外部投资回报延迟，避免在信息不足时继续加码。',
        growth: '放下对结果时间表的执着，修正路线而非否定愿景。',
      },
    },
  },
  {
    id: 'wands-four',
    number: 4,
    arcana: 'minor',
    suit: 'wands',
    rank: 'four',
    nameZh: '权杖四',
    nameEn: 'Four of Wands',
    image: new URL('../../tarot_img/Wands_Four.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['庆祝', '归属', '稳定'],
        general: '阶段成果值得庆祝，稳定环境让人感到被接纳。',
        love: '关系基础稳固，适合公开、订婚或与家人共享喜悦。',
        career: '团队达成里程碑，良好文化提升合作与士气。',
        wealth: '财务基础较稳，可为家庭与重要庆典做合理安排。',
        growth: '珍惜支持你的群体，在归属中补充力量。',
      },
      reversed: {
        keywords: ['不安定', '庆祝延迟', '归属冲突'],
        general: '表面稳定下仍有不协调，家庭或团体关系需要修复。',
        love: '承诺推迟或亲友压力影响关系，应先建立双方边界。',
        career: '团队缺乏凝聚力，成果也因内部问题难以共享。',
        wealth: '居家或庆典开支超出预期，需要重排预算。',
        growth: '不要为融入而压抑自己，寻找更真实的归属方式。',
      },
    },
  },
  {
    id: 'wands-five',
    number: 5,
    arcana: 'minor',
    suit: 'wands',
    rank: 'five',
    nameZh: '权杖五',
    nameEn: 'Five of Wands',
    image: new URL('../../tarot_img/Wands_Five.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['竞争', '摩擦', '多方意见'],
        general: '不同力量正在碰撞，建设性竞争能暴露问题并带来成长。',
        love: '小争执反映真实差异，公平沟通可避免升级。',
        career: '团队观点冲突或竞争激烈，用规则把摩擦转为创意。',
        wealth: '多项需求争夺有限资源，必须明确优先顺序。',
        growth: '在分歧中练习表达立场，也学习听见别人。',
      },
      reversed: {
        keywords: ['回避冲突', '内耗', '争执失控'],
        general: '冲突被压抑或变成无效内耗，需要重新建立讨论方式。',
        love: '冷战与旧争论反复出现，应聚焦核心而非争输赢。',
        career: '办公室竞争走向消耗，避免卷入没有目标的对抗。',
        wealth: '因意见混乱迟迟无法决定，设定清晰财务原则。',
        growth: '看见内在互相矛盾的欲望，先整合再行动。',
      },
    },
  },
  {
    id: 'wands-six',
    number: 6,
    arcana: 'minor',
    suit: 'wands',
    rank: 'six',
    nameZh: '权杖六',
    nameEn: 'Six of Wands',
    image: new URL('../../tarot_img/Wands_Six.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['胜利', '认可', '信心'],
        general: '努力得到公开肯定，带着谦逊接受属于你的成功。',
        love: '关系获得认可，彼此欣赏让感情更有信心。',
        career: '成果被看见，适合展示能力或承担更高职位。',
        wealth: '正确策略带来回报，可继续巩固而非急于炫耀。',
        growth: '承认自己的进步，让健康自信支持下一段旅程。',
      },
      reversed: {
        keywords: ['认可不足', '自负', '挫败'],
        general: '期待的掌声没有到来，或过度在意外界评价。',
        love: '关系中争夺关注与面子，真实连接因此被忽略。',
        career: '成果未被认可或目标落空，需从反馈中校正表现。',
        wealth: '为维持成功形象而消费，会侵蚀实际积累。',
        growth: '把价值从掌声中收回，建立不依赖比较的自信。',
      },
    },
  },
  {
    id: 'wands-seven',
    number: 7,
    arcana: 'minor',
    suit: 'wands',
    rank: 'seven',
    nameZh: '权杖七',
    nameEn: 'Seven of Wands',
    image: new URL('../../tarot_img/Wands_Seven.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['坚守', '挑战', '勇气'],
        general: '立场受到挑战，但清楚底线就有能力守住成果。',
        love: '外部压力需要双方共同面对，也要捍卫关系中的边界。',
        career: '竞争加剧，凭专业与准备坚持自己的位置。',
        wealth: '守住预算和长期策略，不被短期诱惑动摇。',
        growth: '练习在压力下表达“不”，保护真正重要的事。',
      },
      reversed: {
        keywords: ['不堪重负', '放弃', '防御过度'],
        general: '持续防守已经耗尽能量，需要分辨哪些战斗值得继续。',
        love: '过度戒备让亲密难以靠近，或外界压力已超出承受。',
        career: '挑战太多导致退缩，可寻求支援并调整战线。',
        wealth: '财务压力使原则松动，应优先处理最紧迫风险。',
        growth: '放下不必要的证明，保存力量不是软弱。',
      },
    },
  },
  {
    id: 'wands-eight',
    number: 8,
    arcana: 'minor',
    suit: 'wands',
    rank: 'eight',
    nameZh: '权杖八',
    nameEn: 'Eight of Wands',
    image: new URL('../../tarot_img/Wands_Eight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['快速进展', '消息', '动能'],
        general: '阻力突然减少，事件将快速推进，需要及时回应。',
        love: '消息频繁、关系升温，坦率表达能把握当前节奏。',
        career: '项目加速或出差机会出现，保持清晰沟通。',
        wealth: '资金流动变快，及时处理交易但仍要核对细节。',
        growth: '顺势行动，别让过度分析错过已经成熟的时机。',
      },
      reversed: {
        keywords: ['延误', '混乱消息', '急躁'],
        general: '进展被延迟或信息互相冲突，急推只会增加错误。',
        love: '沟通节奏失衡、消息误读，先澄清再作结论。',
        career: '排期与沟通出现阻塞，应重新确认责任和截止点。',
        wealth: '到账或交易延迟，避免在焦虑中重复操作。',
        growth: '把速度慢下来，整理散乱能量后再重新出发。',
      },
    },
  },
  {
    id: 'wands-nine',
    number: 9,
    arcana: 'minor',
    suit: 'wands',
    rank: 'nine',
    nameZh: '权杖九',
    nameEn: 'Nine of Wands',
    image: new URL('../../tarot_img/Wands_Nine.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['韧性', '警觉', '最后坚持'],
        general: '经历考验后仍站立着，最后阶段需要边界与耐力。',
        love: '旧伤让人谨慎，但稳定陪伴能逐步建立信任。',
        career: '项目接近终点，保护成果并为最后挑战做好准备。',
        wealth: '继续守住储备与风险线，不要在终点前松懈。',
        growth: '认可自己的韧性，同时允许疲惫得到照顾。',
      },
      reversed: {
        keywords: ['精疲力竭', '多疑', '防线崩溃'],
        general: '长期戒备已经透支，硬撑可能造成更大损耗。',
        love: '把过去伤害投射到当下，使关系难以建立安全。',
        career: '倦怠削弱判断，应休整、授权或重新评估目标。',
        wealth: '持续财务压力消耗信心，需要寻求实际支持。',
        growth: '松开永久防御，疗愈比证明还能坚持更重要。',
      },
    },
  },
  {
    id: 'wands-ten',
    number: 10,
    arcana: 'minor',
    suit: 'wands',
    rank: 'ten',
    nameZh: '权杖十',
    nameEn: 'Ten of Wands',
    image: new URL('../../tarot_img/Wands_Ten.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['负担', '责任', '接近完成'],
        general: '责任沉重但目标接近完成，需要合理分担而非独扛。',
        love: '现实压力挤压亲密时间，双方应共同承担生活任务。',
        career: '工作量过大，优先完成关键事项并主动授权。',
        wealth: '多项义务造成压力，系统整理债务与固定支出。',
        growth: '看清哪些责任真正属于自己，成熟不等于包办。',
      },
      reversed: {
        keywords: ['卸下重担', '责任失衡', '崩溃边缘'],
        general: '你必须释放不必要负担，否则身心难以继续。',
        love: '长期不公平付出需要被纠正，别再默默承受。',
        career: '任务超载已影响质量，应立即删减或重新谈判。',
        wealth: '债务和承诺难以维持，需要重组而非继续掩盖。',
        growth: '允许求助与放手，把能量还给核心生活。',
      },
    },
  },
  {
    id: 'wands-page',
    number: 11,
    arcana: 'minor',
    suit: 'wands',
    rank: 'page',
    nameZh: '权杖侍从',
    nameEn: 'Page of Wands',
    image: new URL('../../tarot_img/Wands_Page.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['探索', '好消息', '大胆尝试'],
        general: '充满好奇的新消息或机会到来，适合边学边试。',
        love: '轻快热情的互动出现，先享受认识过程而不急于定义。',
        career: '新领域值得探索，实习、学习或创意提案都有利。',
        wealth: '尝试培养可变现的新技能，但从低成本开始。',
        growth: '保护初心的兴奋感，让好奇带你跨出舒适圈。',
      },
      reversed: {
        keywords: ['三分钟热度', '坏消息', '缺乏方向'],
        general: '热情分散且难以坚持，计划可能停在想象阶段。',
        love: '暧昧反复或态度幼稚，需要看行动而非口头热度。',
        career: '创意很多却缺少执行，先完成一个小成果。',
        wealth: '冲动尝试新财路可能浪费资源，先验证基本可行性。',
        growth: '接受自己仍在学习，用纪律保护而非压灭热情。',
      },
    },
  },
  {
    id: 'wands-knight',
    number: 12,
    arcana: 'minor',
    suit: 'wands',
    rank: 'knight',
    nameZh: '权杖骑士',
    nameEn: 'Knight of Wands',
    image: new URL('../../tarot_img/Wands_Knight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['冒险', '冲劲', '魅力'],
        general: '强烈行动力推动局势，勇敢前进同时保持方向。',
        love: '热烈追求与强大吸引力出现，关系节奏明显加快。',
        career: '适合出击、提案或开拓新市场，行动会带来关注。',
        wealth: '积极争取收入机会，但应给冒险设定上限。',
        growth: '用身体与行动体验生命，不再只在脑中计划。',
      },
      reversed: {
        keywords: ['冲动', '躁进', '不稳定'],
        general: '行动缺乏耐心与后续，热情可能变成破坏性冲动。',
        love: '来得快去得快的激情难以承诺，留意忽冷忽热。',
        career: '仓促决策、频繁换向导致项目失控，应先停下来。',
        wealth: '投机与冲动消费风险上升，拒绝追逐刺激。',
        growth: '练习让火焰持续燃烧，而非每次都烧尽自己。',
      },
    },
  },
  {
    id: 'wands-queen',
    number: 13,
    arcana: 'minor',
    suit: 'wands',
    rank: 'queen',
    nameZh: '权杖王后',
    nameEn: 'Queen of Wands',
    image: new URL('../../tarot_img/Wands_Queen.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['自信', '魅力', '独立'],
        general: '温暖自信的影响力吸引资源，忠于自己就能鼓舞他人。',
        love: '坦率魅力与健康独立让关系充满热度和尊重。',
        career: '适合领导创意、公开表达并建立有感染力的团队。',
        wealth: '相信自己的创造能力，也能务实管理收入与生活。',
        growth: '占据自己的位置，不因他人目光缩小光芒。',
      },
      reversed: {
        keywords: ['嫉妒', '缺乏自信', '强势'],
        general: '外在强硬可能掩盖不安全感，比较心正在消耗能量。',
        love: '嫉妒或争夺注意力伤害信任，需要回到自我价值。',
        career: '控制欲和情绪化领导引发反感，应多听取反馈。',
        wealth: '为证明地位而消费，会让财务失去真实尺度。',
        growth: '停止和别人竞争光芒，重新肯定独特优势。',
      },
    },
  },
  {
    id: 'wands-king',
    number: 14,
    arcana: 'minor',
    suit: 'wands',
    rank: 'king',
    nameZh: '权杖国王',
    nameEn: 'King of Wands',
    image: new URL('../../tarot_img/Wands_King.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['远见领导', '创业', '果断'],
        general: '远见与成熟行动力结合，适合带领他人实现宏大目标。',
        love: '热情且愿意担当，关系需要平等欣赏与明确承诺。',
        career: '展现战略领导力，创业、管理或扩张计划进展有利。',
        wealth: '以长期愿景配置资源，敢于投资也能控制风险。',
        growth: '把个人热情转化为能服务更多人的方向。',
      },
      reversed: {
        keywords: ['专横', '鲁莽领导', '期望过高'],
        general: '强烈意志缺少倾听，愿景可能沦为自我中心。',
        love: '支配欲和脾气让伴侣难以表达，需要放下权威姿态。',
        career: '领导急躁或承诺过度，团队信任正在下降。',
        wealth: '过度自信推动高风险决策，应引入独立审查。',
        growth: '真正的领导先能管理自己，也允许别人有不同道路。',
      },
    },
  },
];

const cups: TarotCard[] = [
  {
    id: 'cups-ace',
    number: 1,
    arcana: 'minor',
    suit: 'cups',
    rank: 'ace',
    nameZh: '圣杯王牌',
    nameEn: 'Ace of Cups',
    image: new URL('../../tarot_img/Cups_Ace.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['情感新生', '爱', '直觉'],
        general: '情感之杯正在注满，新的爱与疗愈有空间进入。',
        love: '真挚感情萌芽，适合敞开心扉表达温柔与好感。',
        career: '有意义的新机会带来满足，创意与同理心尤其有利。',
        wealth: '财务改善伴随安心感，也可能收到善意支持。',
        growth: '允许感受自然流动，学习接收爱而不急着回报。',
      },
      reversed: {
        keywords: ['情感压抑', '空虚', '爱受阻'],
        general: '情绪被堵住或过度外溢，需要先照顾内在容器。',
        love: '害怕受伤而关闭心门，或付出没有得到回应。',
        career: '工作缺乏情感认同，创意也因压抑而停滞。',
        wealth: '用金钱补偿空虚难以奏效，应先处理情绪需求。',
        growth: '把向外倾倒的关怀收回一些，重新滋养自己。',
      },
    },
  },
  {
    id: 'cups-two',
    number: 2,
    arcana: 'minor',
    suit: 'cups',
    rank: 'two',
    nameZh: '圣杯二',
    nameEn: 'Two of Cups',
    image: new URL('../../tarot_img/Cups_Two.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['互相吸引', '伙伴关系', '和解'],
        general: '平等交换与真诚回应促成重要联结。',
        love: '双方情感互通，适合确认关系、和解或深化承诺。',
        career: '默契合作与公平协议能带来双赢成果。',
        wealth: '可信伙伴或共同规划有助于改善财务。',
        growth: '在关系镜像中认识自己，也保持完整边界。',
      },
      reversed: {
        keywords: ['失和', '不对等', '沟通破裂'],
        general: '原本的互信出现裂缝，交换关系失去平衡。',
        love: '误解、冷淡或付出不对等需要直接面对。',
        career: '合作条款或价值观不合，先澄清再继续投入。',
        wealth: '共同财务分配不公，应把责任和数字说清楚。',
        growth: '不再通过迎合换取联结，先修复与自己的关系。',
      },
    },
  },
  {
    id: 'cups-three',
    number: 3,
    arcana: 'minor',
    suit: 'cups',
    rank: 'three',
    nameZh: '圣杯三',
    nameEn: 'Three of Cups',
    image: new URL('../../tarot_img/Cups_Three.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['友谊', '庆祝', '支持'],
        general: '共享喜悦与社群支持带来情感补给。',
        love: '轻松社交增添快乐，单身者可能经朋友结识缘分。',
        career: '团队合作顺畅，适合庆祝成果并扩大人脉。',
        wealth: '可为聚会预留合理预算，也可能获得朋友资源。',
        growth: '让可靠朋友见证你的喜怒，不必独自消化一切。',
      },
      reversed: {
        keywords: ['过度社交', '闲言', '第三方干扰'],
        general: '表面热闹掩盖内耗，团体边界可能变得混乱。',
        love: '第三方意见、暧昧或流言影响双方信任。',
        career: '小圈子与八卦削弱协作，应回到正式沟通。',
        wealth: '应酬和享乐开销失控，需要暂停人情消费。',
        growth: '分辨真支持与表面合群，给自己安静空间。',
      },
    },
  },
  {
    id: 'cups-four',
    number: 4,
    arcana: 'minor',
    suit: 'cups',
    rank: 'four',
    nameZh: '圣杯四',
    nameEn: 'Four of Cups',
    image: new URL('../../tarot_img/Cups_Four.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['冷淡', '沉思', '错过机会'],
        general: '对现状提不起兴趣，内省有益但别忽略眼前邀请。',
        love: '情感疲倦让人疏离，需要确认是暂时低潮还是不再投入。',
        career: '工作倦怠削弱热情，新机会可能因消极而被忽略。',
        wealth: '物质满足感下降，适合重新定义真正需要。',
        growth: '允许无聊揭示深层渴望，同时保持对世界开放。',
      },
      reversed: {
        keywords: ['重新投入', '觉醒', '走出停滞'],
        general: '麻木开始松动，你愿意重新看见机会与连接。',
        love: '走出情感退缩，愿意回应对方或认识新的人。',
        career: '重新找到动力，适合接受曾经忽视的可能。',
        wealth: '财务态度转为主动，开始整理并寻找改善方案。',
        growth: '从长期内省回到生活，用小行动恢复参与感。',
      },
    },
  },
  {
    id: 'cups-five',
    number: 5,
    arcana: 'minor',
    suit: 'cups',
    rank: 'five',
    nameZh: '圣杯五',
    nameEn: 'Five of Cups',
    image: new URL('../../tarot_img/Cups_Five.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['失落', '遗憾', '哀伤'],
        general: '失去值得哀悼，但仍有资源与关系尚未离开。',
        love: '分离或失望带来悲伤，先允许情绪再看见剩余的爱。',
        career: '项目落空令人沮丧，经验仍可成为下一步基础。',
        wealth: '财务损失需要面对，也要盘点仍可保全的部分。',
        growth: '让哀伤被看见，不把一次失去变成全部人生。',
      },
      reversed: {
        keywords: ['接受', '释怀', '重新看见希望'],
        general: '你开始从遗憾中抬头，愿意接受现实并继续生活。',
        love: '旧伤逐渐松开，和解或新的情感空间正在形成。',
        career: '从失败提取教训后，能量开始回到未来。',
        wealth: '停止沉溺损失，着手恢复储备与现金流。',
        growth: '原谅无法改变的过去，把注意力还给当下。',
      },
    },
  },
  {
    id: 'cups-six',
    number: 6,
    arcana: 'minor',
    suit: 'cups',
    rank: 'six',
    nameZh: '圣杯六',
    nameEn: 'Six of Cups',
    image: new URL('../../tarot_img/Cups_Six.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['回忆', '纯真', '故人'],
        general: '温暖往事或熟悉的人重新出现，带来单纯慰藉。',
        love: '旧缘、青梅竹马或纯真相处成为关系主题。',
        career: '过去技能与人脉重新有用，熟悉领域带来机会。',
        wealth: '家人支持或旧资源帮助稳定当前财务。',
        growth: '拥抱内在小孩，让过去的美好成为滋养。',
      },
      reversed: {
        keywords: ['困在过去', '过度怀旧', '长大'],
        general: '美化往事让现实失色，需要从旧模式中走出来。',
        love: '旧情纠缠或童年模式影响当下亲密。',
        career: '沿用过时方法限制发展，必须适应新环境。',
        wealth: '过去的金钱观不再适合现在，应建立成人责任。',
        growth: '疗愈旧经验但不退回旧身份，允许自己成熟。',
      },
    },
  },
  {
    id: 'cups-seven',
    number: 7,
    arcana: 'minor',
    suit: 'cups',
    rank: 'seven',
    nameZh: '圣杯七',
    nameEn: 'Seven of Cups',
    image: new URL('../../tarot_img/Cups_Seven.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['幻想', '多重选择', '诱惑'],
        general: '可能性很多却真假混杂，需要用价值与事实筛选。',
        love: '理想化对象或选择过多，使真诚投入变得困难。',
        career: '机会看似丰富，先辨别可行性再选一个方向。',
        wealth: '高回报诱惑增多，拒绝看不懂的承诺。',
        growth: '让想象服务创造，而不是代替现实行动。',
      },
      reversed: {
        keywords: ['看清选择', '聚焦', '幻想破灭'],
        general: '迷雾逐渐散去，你准备舍弃幻象并做出决定。',
        love: '不再理想化关系，能够面对真实的人与需求。',
        career: '方向收敛，选定优先事项后执行力恢复。',
        wealth: '识破不切实际方案，资金回到务实安排。',
        growth: '接受选择意味着放弃其他可能，专注带来自由。',
      },
    },
  },
  {
    id: 'cups-eight',
    number: 8,
    arcana: 'minor',
    suit: 'cups',
    rank: 'eight',
    nameZh: '圣杯八',
    nameEn: 'Eight of Cups',
    image: new URL('../../tarot_img/Cups_Eight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['离开', '寻找意义', '放下'],
        general: '即使投入很多，也到了离开不再满足之事的时刻。',
        love: '情感需求长期未被回应，可能需要距离或告别。',
        career: '成就缺乏意义，适合寻找更符合价值的道路。',
        wealth: '放弃不健康的消费或收益模式，为长期稳定转向。',
        growth: '勇敢离开熟悉空壳，追寻更深层的真实。',
      },
      reversed: {
        keywords: ['害怕离开', '徘徊', '仓促返回'],
        general: '明知不满足却迟迟无法走开，或离开后又反复回头。',
        love: '关系去留摇摆不定，需要诚实面对恐惧与代价。',
        career: '因安全感留在消耗职位，转变计划尚未成熟。',
        wealth: '害怕短期损失而继续无效投入，应设清楚止损点。',
        growth: '先弄明白真正寻找什么，再决定留下或出发。',
      },
    },
  },
  {
    id: 'cups-nine',
    number: 9,
    arcana: 'minor',
    suit: 'cups',
    rank: 'nine',
    nameZh: '圣杯九',
    nameEn: 'Nine of Cups',
    image: new URL('../../tarot_img/Cups_Nine.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['满足', '愿望实现', '享受'],
        general: '心愿接近实现，可以带着感恩享受丰足时刻。',
        love: '感情带来愉悦与满足，单身也能自在享受自己。',
        career: '期待成果达成，专业表现带来成就感。',
        wealth: '财务舒适度提升，适合适度犒赏并继续储蓄。',
        growth: '认可已有幸福，不把满足无限推迟到未来。',
      },
      reversed: {
        keywords: ['不满足', '纵欲', '愿望落空'],
        general: '外在拥有未能填补内心，过量享受反而留下空虚。',
        love: '只追求被满足或理想结局，忽视真实互相理解。',
        career: '成绩未带来预期快乐，需要重问成功的定义。',
        wealth: '奢侈和即时享乐侵蚀积累，减少补偿性消费。',
        growth: '从外在奖赏转向内在价值，练习知足但不麻木。',
      },
    },
  },
  {
    id: 'cups-ten',
    number: 10,
    arcana: 'minor',
    suit: 'cups',
    rank: 'ten',
    nameZh: '圣杯十',
    nameEn: 'Ten of Cups',
    image: new URL('../../tarot_img/Cups_Ten.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['情感圆满', '家庭', '和谐'],
        general: '长久联结与共同价值带来深层幸福和归属。',
        love: '关系和谐稳定，适合组建家庭或庆祝共同愿景。',
        career: '支持性的团队环境让工作与生活更协调。',
        wealth: '家庭财务稳定，共同规划能惠及长期生活。',
        growth: '把幸福理解为共享与连接，而非个人占有。',
      },
      reversed: {
        keywords: ['家庭失和', '理想破裂', '价值分歧'],
        general: '理想中的和谐与现实有落差，关系结构需要修复。',
        love: '家庭压力或长期愿景不同，不能再维持表面圆满。',
        career: '团队价值不一致，归属感与士气明显下降。',
        wealth: '家庭成员财务目标冲突，应重建透明协商。',
        growth: '放下完美家庭脚本，创造更真实的联结方式。',
      },
    },
  },
  {
    id: 'cups-page',
    number: 11,
    arcana: 'minor',
    suit: 'cups',
    rank: 'page',
    nameZh: '圣杯侍从',
    nameEn: 'Page of Cups',
    image: new URL('../../tarot_img/Cups_Page.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['情感消息', '敏感', '想象力'],
        general: '温柔消息或意外灵感到来，保持开放与童真。',
        love: '告白、道歉或新的心动可能出现，真诚胜过技巧。',
        career: '创意与直觉带来新点子，适合学习艺术或助人技能。',
        wealth: '小额好消息可能出现，也要学习更成熟地管理金钱。',
        growth: '尊重细腻感受，让想象力有安全的表达出口。',
      },
      reversed: {
        keywords: ['情绪幼稚', '逃避现实', '创意受阻'],
        general: '敏感变成过度反应，幻想也可能掩盖现实。',
        love: '情绪化信息或不成熟承诺让关系难以信任。',
        career: '害怕批评而不敢展示创意，或想法缺少实际支撑。',
        wealth: '凭感觉花钱、忽略账单，需要建立基础习惯。',
        growth: '照顾内在小孩但不让它掌舵，学习调节情绪。',
      },
    },
  },
  {
    id: 'cups-knight',
    number: 12,
    arcana: 'minor',
    suit: 'cups',
    rank: 'knight',
    nameZh: '圣杯骑士',
    nameEn: 'Knight of Cups',
    image: new URL('../../tarot_img/Cups_Knight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['浪漫', '邀请', '追随内心'],
        general: '带着理想与情感前进，一份邀请可能打开新的体验。',
        love: '浪漫示好、求爱或温柔承诺让关系向前。',
        career: '凭创意和人际魅力推进提案，适合有意义的合作。',
        wealth: '可把兴趣转化为收入，但仍需实际执行计划。',
        growth: '让心指引方向，同时用现实行动承载理想。',
      },
      reversed: {
        keywords: ['空头承诺', '情绪操控', '不切实际'],
        general: '漂亮想象缺少行动，情绪也可能被用来逃避责任。',
        love: '甜言蜜语与实际表现不一致，警惕理想化和欺骗。',
        career: '提案过于浪漫却缺乏细节，应补足数据与时间表。',
        wealth: '因梦想项目投入过多，先确认商业可行性。',
        growth: '不沉醉于“应该怎样”的故事，回到真实感受。',
      },
    },
  },
  {
    id: 'cups-queen',
    number: 13,
    arcana: 'minor',
    suit: 'cups',
    rank: 'queen',
    nameZh: '圣杯王后',
    nameEn: 'Queen of Cups',
    image: new URL('../../tarot_img/Cups_Queen.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['同理心', '直觉', '情感成熟'],
        general: '温柔理解与敏锐直觉帮助你承接复杂情绪。',
        love: '深度倾听与稳定关怀让关系感到安全。',
        career: '适合辅导、创意与照顾型工作，以同理心带领合作。',
        wealth: '凭直觉察觉需求，但财务决定仍保持温和理性。',
        growth: '拥抱敏感天赋，也为自己保留情绪边界。',
      },
      reversed: {
        keywords: ['情绪淹没', '过度依赖', '边界模糊'],
        general: '吸收太多他人情绪，使自己的需要被忽略。',
        love: '过度照顾、依赖或情绪操控造成关系失衡。',
        career: '同理心疲劳影响判断，需要界定工作责任。',
        wealth: '因内疚或同情承担不合理支出，先保护基本安全。',
        growth: '分清自己的感受和别人的感受，停止以牺牲换爱。',
      },
    },
  },
  {
    id: 'cups-king',
    number: 14,
    arcana: 'minor',
    suit: 'cups',
    rank: 'king',
    nameZh: '圣杯国王',
    nameEn: 'King of Cups',
    image: new URL('../../tarot_img/Cups_King.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['情绪稳定', '慈悲领导', '外交'],
        general: '深厚情感被成熟地承载，冷静与温柔可以并存。',
        love: '关系中愿意倾听和负责，情感稳定而不失温度。',
        career: '以情商处理复杂人际，适合调解与稳健领导。',
        wealth: '面对波动保持平静，做兼顾现实与价值的决定。',
        growth: '不压抑也不被情绪淹没，成为自己的安全港。',
      },
      reversed: {
        keywords: ['情绪压制', '冷漠', '操控'],
        general: '表面平静下情绪积压，可能以被动方式控制局面。',
        love: '情感不表达或利用冷淡施压，使伴侣难以靠近。',
        career: '情绪偏见隐藏在理性外表下，应避免暗中操纵。',
        wealth: '焦虑被否认后转成错误决定，需要正视真实感受。',
        growth: '放下永远镇定的面具，以安全方式表达脆弱。',
      },
    },
  },
];

const swords: TarotCard[] = [
  {
    id: 'swords-ace',
    number: 1,
    arcana: 'minor',
    suit: 'swords',
    rank: 'ace',
    nameZh: '宝剑王牌',
    nameEn: 'Ace of Swords',
    image: new URL('../../tarot_img/Swords_Ace.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['清晰', '真相', '突破'],
        general: '思路突然清晰，诚实判断能切开长期混乱。',
        love: '坦白对话带来突破，关系需要真实而非猜测。',
        career: '新策略、决定或沟通机会出现，逻辑会赢得支持。',
        wealth: '看清数字与条款后，可做出果断而理性的安排。',
        growth: '用诚实语言命名经验，让思想服务真实。',
      },
      reversed: {
        keywords: ['混乱', '误判', '言语伤害'],
        general: '信息矛盾或思考失焦，仓促结论容易伤人。',
        love: '沟通尖锐、误解加深，先确认事实再表达判断。',
        career: '计划逻辑不足或指令不清，应重新梳理核心问题。',
        wealth: '合同细节可能模糊，暂缓签署并寻求专业复核。',
        growth: '觉察批判性思维何时变成自我攻击。',
      },
    },
  },
  {
    id: 'swords-two',
    number: 2,
    arcana: 'minor',
    suit: 'swords',
    rank: 'two',
    nameZh: '宝剑二',
    nameEn: 'Two of Swords',
    image: new URL('../../tarot_img/Swords_Two.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['僵局', '回避决定', '权衡'],
        general: '两个选择势均力敌，但封闭信息无法维持长久平衡。',
        love: '双方回避敏感议题，表面和平下仍需做出选择。',
        career: '决策卡住，补充事实并明确优先级才能前进。',
        wealth: '财务方案难以取舍，先暂停非必要行动。',
        growth: '放下假装不知道，温柔面对决定背后的情绪。',
      },
      reversed: {
        keywords: ['信息过载', '决定浮现', '内在冲突'],
        general: '僵局开始松动，也可能因信息太多更加焦虑。',
        love: '隐藏问题浮上台面，必须停止拖延并诚实回应。',
        career: '被推迟的决定迫近，筛除噪音后选择可承担方案。',
        wealth: '财务压力迫使取舍，优先保护基本现金流。',
        growth: '接纳没有完美答案，以价值而非恐惧做决定。',
      },
    },
  },
  {
    id: 'swords-three',
    number: 3,
    arcana: 'minor',
    suit: 'swords',
    rank: 'three',
    nameZh: '宝剑三',
    nameEn: 'Three of Swords',
    image: new URL('../../tarot_img/Swords_Three.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['心碎', '悲痛', '真相刺痛'],
        general: '痛苦真相已经显现，承认伤口是疗愈的开始。',
        love: '分离、背叛或尖锐话语带来真实心痛。',
        career: '坏消息或合作破裂令人失望，需要消化再重整。',
        wealth: '财务损失或意外账单造成压力，应理性处理。',
        growth: '不压抑悲伤，让痛苦穿过而不是定义自己。',
      },
      reversed: {
        keywords: ['疗愈', '释放悲伤', '旧伤反复'],
        general: '伤口开始愈合，或被压抑的痛仍需要更深处理。',
        love: '愿意原谅和修复，但不能跳过责任与真实感受。',
        career: '逐渐走出挫折，可从失败中恢复专业信心。',
        wealth: '损失进入修复期，建立计划有助于减轻焦虑。',
        growth: '把伤痛转化为理解，不再反复惩罚自己。',
      },
    },
  },
  {
    id: 'swords-four',
    number: 4,
    arcana: 'minor',
    suit: 'swords',
    rank: 'four',
    nameZh: '宝剑四',
    nameEn: 'Four of Swords',
    image: new URL('../../tarot_img/Swords_Four.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['休息', '恢复', '静思'],
        general: '身心需要暂停，安静恢复会为下一步保存力量。',
        love: '关系适合暂时降速，各自整理情绪而非继续争执。',
        career: '短暂休假或战略停顿有助于避免错误和倦怠。',
        wealth: '减少交易与消费，利用平静期整理财务。',
        growth: '把休息视为必要实践，而不是偷懒或失败。',
      },
      reversed: {
        keywords: ['倦怠', '躁动', '被迫恢复'],
        general: '休息不足已转为耗竭，或停滞太久开始焦躁。',
        love: '冷静期没有真正修复问题，关系需重新沟通。',
        career: '过劳影响表现，身体可能迫使你停止工作。',
        wealth: '焦虑驱动频繁操作，先恢复理性再决定。',
        growth: '识别无法放松的根源，建立可持续的恢复节奏。',
      },
    },
  },
  {
    id: 'swords-five',
    number: 5,
    arcana: 'minor',
    suit: 'swords',
    rank: 'five',
    nameZh: '宝剑五',
    nameEn: 'Five of Swords',
    image: new URL('../../tarot_img/Swords_Five.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['冲突', '空洞胜利', '敌意'],
        general: '赢下争执却可能失去关系，代价需要被认真衡量。',
        love: '讽刺、争输赢或旧怨伤害亲密，及时停止攻击。',
        career: '办公室权斗和不择手段会留下长期后果。',
        wealth: '短期获利若建立在欺瞒上，风险将随后出现。',
        growth: '分辨维护尊严与证明自己，选择不制造更多伤害。',
      },
      reversed: {
        keywords: ['和解', '怨恨未消', '停止争斗'],
        general: '你有机会放下争斗，但隐藏怨气仍需处理。',
        love: '道歉与修复成为可能，前提是不掩盖真正伤害。',
        career: '退出无效权斗，重建合作或选择离开有毒环境。',
        wealth: '解决争议费用或不公平交易，优先恢复诚信。',
        growth: '承认自己在冲突中的角色，不再靠胜负确认价值。',
      },
    },
  },
  {
    id: 'swords-six',
    number: 6,
    arcana: 'minor',
    suit: 'swords',
    rank: 'six',
    nameZh: '宝剑六',
    nameEn: 'Six of Swords',
    image: new URL('../../tarot_img/Swords_Six.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['过渡', '离开困境', '疗愈旅程'],
        general: '你正离开动荡水域，过程缓慢却朝向更平静处。',
        love: '双方尝试走出冲突，或以成熟方式结束一段关系。',
        career: '转岗、搬迁或方法调整带来逐步改善。',
        wealth: '经过困难后开始稳定，继续采用保守复原计划。',
        growth: '带着经验前行，不要求自己立刻忘记过去。',
      },
      reversed: {
        keywords: ['无法前进', '旧问题回返', '过渡受阻'],
        general: '你想离开困境，却仍被未处理的问题拉回。',
        love: '旧争议反复出现，距离没有替代真正解决。',
        career: '转变计划受阻或环境问题被带到新位置。',
        wealth: '财务复原迟缓，隐藏债务需要先被处理。',
        growth: '停止只换环境，面对内在仍携带的负担。',
      },
    },
  },
  {
    id: 'swords-seven',
    number: 7,
    arcana: 'minor',
    suit: 'swords',
    rank: 'seven',
    nameZh: '宝剑七',
    nameEn: 'Seven of Swords',
    image: new URL('../../tarot_img/Swords_Seven.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['策略', '隐瞒', '独自行动'],
        general: '需要谨慎策略，但隐瞒与捷径也会带来信任风险。',
        love: '关系中可能有所保留或逃避坦白，应观察言行一致性。',
        career: '低调规划有利，涉及伦理时不要用聪明代替诚信。',
        wealth: '保护隐私与防范欺诈，同时避免灰色财务手段。',
        growth: '审视自己为何不敢直面问题，选择更诚实的策略。',
      },
      reversed: {
        keywords: ['真相揭露', '坦白', '自我欺骗'],
        general: '隐藏行为难以继续，坦白或被揭露成为转折。',
        love: '秘密浮现，诚实承担后果才可能重建信任。',
        career: '不当策略被发现，及时纠正比继续掩饰更重要。',
        wealth: '诈骗风险曝光或账目漏洞显现，应立刻核查。',
        growth: '停止对自己说谎，把聪明用于解决而非逃避。',
      },
    },
  },
  {
    id: 'swords-eight',
    number: 8,
    arcana: 'minor',
    suit: 'swords',
    rank: 'eight',
    nameZh: '宝剑八',
    nameEn: 'Eight of Swords',
    image: new URL('../../tarot_img/Swords_Eight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['受困', '限制信念', '无力感'],
        general: '困境部分来自思维限制，实际选择比想象中更多。',
        love: '害怕冲突或离开让人感觉被困，需要看见自身权力。',
        career: '自我怀疑限制行动，先验证哪些障碍是真实的。',
        wealth: '财务压力造成无助感，可从一项可控数字开始整理。',
        growth: '觉察“我不能”的故事，并尝试一个小小反证。',
      },
      reversed: {
        keywords: ['挣脱', '新视角', '恢复自主'],
        general: '限制正在松动，你开始看见出口并愿意负责。',
        love: '走出恐惧与被动，准备表达边界或离开束缚。',
        career: '信心恢复，能够主动争取资源与新的选择。',
        wealth: '开始面对债务或收入问题，实际行动带来自由。',
        growth: '把选择权收回，不再让旧信念替你决定。',
      },
    },
  },
  {
    id: 'swords-nine',
    number: 9,
    arcana: 'minor',
    suit: 'swords',
    rank: 'nine',
    nameZh: '宝剑九',
    nameEn: 'Nine of Swords',
    image: new URL('../../tarot_img/Swords_Nine.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['焦虑', '失眠', '内疚'],
        general: '担忧在夜里被放大，痛苦真实但最坏想象未必是事实。',
        love: '害怕失去或内疚影响亲密，独自猜测会加重负担。',
        career: '工作压力与完美主义导致失眠，需要及时求助。',
        wealth: '财务焦虑反复盘旋，应把模糊恐惧转成具体数字。',
        growth: '以同理心面对忧虑，不因需要支持而羞耻。',
      },
      reversed: {
        keywords: ['焦虑缓解', '面对恐惧', '绝望加深'],
        general: '你开始走出精神折磨，或压抑过久已到临界点。',
        love: '愿意说出担忧可带来缓解，持续恶化则需外部支持。',
        career: '压力源逐渐清楚，调整负荷和期待能恢复状态。',
        wealth: '面对账目后不确定感下降，可执行修复计划。',
        growth: '让可信的人进入内心黑夜，不再独自承担。',
      },
    },
  },
  {
    id: 'swords-ten',
    number: 10,
    arcana: 'minor',
    suit: 'swords',
    rank: 'ten',
    nameZh: '宝剑十',
    nameEn: 'Ten of Swords',
    image: new URL('../../tarot_img/Swords_Ten.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['痛苦终点', '背叛', '结束'],
        general: '艰难局面已经到尽头，最黑暗处也意味着循环结束。',
        love: '关系或信任遭遇决定性结束，需要停止否认。',
        career: '项目、职位或合作彻底终止，下一步是保存自己。',
        wealth: '财务低谷要求止损并接受旧方案已经失败。',
        growth: '不把结束解释为自身毫无价值，允许新的黎明到来。',
      },
      reversed: {
        keywords: ['复原', '拒绝结束', '残余痛苦'],
        general: '最坏阶段正在过去，但抓住旧痛会拖慢复原。',
        love: '关系尝试从重伤中恢复，必须确认是否仍有真实基础。',
        career: '危机后逐渐重建，也要避免重返同一消耗模式。',
        wealth: '脱离最低点，持续修复比追求快速翻身重要。',
        growth: '承认仍在痛，却不再让痛苦决定未来。',
      },
    },
  },
  {
    id: 'swords-page',
    number: 11,
    arcana: 'minor',
    suit: 'swords',
    rank: 'page',
    nameZh: '宝剑侍从',
    nameEn: 'Page of Swords',
    image: new URL('../../tarot_img/Swords_Page.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['好奇', '警觉', '新观点'],
        general: '求知欲旺盛，新信息促使你提问并保持警醒。',
        love: '需要更多了解与坦率对话，别用观察代替互动。',
        career: '适合研究、写作和学习，敏锐思维带来机会。',
        wealth: '主动学习财务知识，仔细阅读每项条款。',
        growth: '保持开放提问，也让观点经过事实检验。',
      },
      reversed: {
        keywords: ['流言', '草率言论', '过度监视'],
        general: '信息未经核实便传播，敏锐可能变成多疑。',
        love: '偷看、试探或口无遮拦破坏信任，需要直接沟通。',
        career: '准备不足却急于发言，先研究再表达立场。',
        wealth: '小道消息诱导决定，不要凭传闻进行交易。',
        growth: '练习谦逊，承认聪明并不等于已经了解全貌。',
      },
    },
  },
  {
    id: 'swords-knight',
    number: 12,
    arcana: 'minor',
    suit: 'swords',
    rank: 'knight',
    nameZh: '宝剑骑士',
    nameEn: 'Knight of Swords',
    image: new URL('../../tarot_img/Swords_Knight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['果断', '直冲目标', '智识行动'],
        general: '目标清楚且行动迅速，勇气需要策略来保持准确。',
        love: '直白表达打破暧昧，但也要给对方回应空间。',
        career: '适合攻克难题、辩护观点或快速推进任务。',
        wealth: '果断处理财务问题有利，前提是数据完整。',
        growth: '把思想转成行动，同时学习速度与体贴并存。',
      },
      reversed: {
        keywords: ['鲁莽', '攻击性', '方向错误'],
        general: '速度与锋芒失去控制，可能冲向未经验证的目标。',
        love: '争辩和逼迫伤害关系，停下来听懂对方再回应。',
        career: '仓促执行或言辞尖锐造成返工与冲突。',
        wealth: '快速交易和高杠杆风险突出，立即降低冲动。',
        growth: '观察急于证明正确的冲动，练习先理解后行动。',
      },
    },
  },
  {
    id: 'swords-queen',
    number: 13,
    arcana: 'minor',
    suit: 'swords',
    rank: 'queen',
    nameZh: '宝剑王后',
    nameEn: 'Queen of Swords',
    image: new URL('../../tarot_img/Swords_Queen.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['独立', '洞察', '清晰边界'],
        general: '经验带来锐利洞察，以诚实和边界处理复杂局面。',
        love: '需要尊重、真实与思想交流，不接受含糊操控。',
        career: '客观分析与直接沟通使你成为可靠决策者。',
        wealth: '理性审查数字与风险，不因情面破坏原则。',
        growth: '让智慧包含温度，也不因同情放弃边界。',
      },
      reversed: {
        keywords: ['尖刻', '冷酷', '偏见'],
        general: '受伤经验让判断变得严苛，真话也可能被用作武器。',
        love: '防御与批判阻断亲密，需要分清界限和惩罚。',
        career: '刻薄沟通或先入为主削弱团队信任。',
        wealth: '恐惧导致过度紧缩或不近人情的决定。',
        growth: '承认锋利背后的伤，培养不牺牲清晰的慈悲。',
      },
    },
  },
  {
    id: 'swords-king',
    number: 14,
    arcana: 'minor',
    suit: 'swords',
    rank: 'king',
    nameZh: '宝剑国王',
    nameEn: 'King of Swords',
    image: new URL('../../tarot_img/Swords_King.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['理性权威', '公正', '战略'],
        general: '清晰原则与成熟判断能够建立公正秩序。',
        love: '关系重视诚实和尊重，情感表达可更有温度。',
        career: '适合法律、策略与管理决策，以事实建立权威。',
        wealth: '采用严谨规则管理资产，重要决定可咨询专家。',
        growth: '训练思辨与伦理，让知识承担责任。',
      },
      reversed: {
        keywords: ['滥用权力', '冷酷判断', '操纵'],
        general: '智慧被用来控制或合理化私利，权威失去公信。',
        love: '冷处理、说教或智力压制让关系无法平等。',
        career: '独断领导与不透明决策造成恐惧和反抗。',
        wealth: '复杂规则可能掩盖不公利益，务必寻求独立意见。',
        growth: '放下永远正确的姿态，让理性接受良知检验。',
      },
    },
  },
];

const pentacles: TarotCard[] = [
  {
    id: 'pentacles-ace',
    number: 1,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'ace',
    nameZh: '星币王牌',
    nameEn: 'Ace of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Ace.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['物质机会', '新基础', '丰盛种子'],
        general: '一个务实机会出现，细心培育可形成长期成果。',
        love: '关系有稳定发展的潜力，实际投入比华丽承诺重要。',
        career: '新工作、项目或技能训练带来可靠起点。',
        wealth: '收入或投资机会值得把握，先建立明确计划。',
        growth: '通过身体、习惯与日常行动把愿景落地。',
      },
      reversed: {
        keywords: ['错失机会', '计划不稳', '资源浪费'],
        general: '现实机会因准备不足或错误优先级而难以扎根。',
        love: '关系缺少实际投入，安全感承诺停留在口头。',
        career: '新项目资源不足或执行失误，应重做基本评估。',
        wealth: '投资条件不成熟，警惕贪快和隐藏成本。',
        growth: '回到基本生活秩序，别让宏大目标悬在空中。',
      },
    },
  },
  {
    id: 'pentacles-two',
    number: 2,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'two',
    nameZh: '星币二',
    nameEn: 'Two of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Two.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['平衡', '灵活调度', '多任务'],
        general: '多项责任同时运转，灵活排序能维持动态平衡。',
        love: '忙碌生活需要刻意安排相处时间与共同责任。',
        career: '能够处理多任务，但要持续调整轻重缓急。',
        wealth: '现金流需精细调度，预算弹性比固定幻想实用。',
        growth: '在变化中练习适应，不要求一切永远静止。',
      },
      reversed: {
        keywords: ['失衡', '超载', '财务混乱'],
        general: '责任超过承受范围，反复救火已难以维持。',
        love: '总把关系排在最后，会让对方感到被忽略。',
        career: '任务管理失控，必须删减、延期或寻求协助。',
        wealth: '账单与现金流错配，立即建立清楚优先级。',
        growth: '承认精力有限，放下一项负担才能找回平衡。',
      },
    },
  },
  {
    id: 'pentacles-three',
    number: 3,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'three',
    nameZh: '星币三',
    nameEn: 'Three of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Three.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['合作', '技艺', '共同建设'],
        general: '不同专长在清晰分工下结合，品质因此提升。',
        love: '双方愿意把关系当作共同项目，实际磨合带来稳定。',
        career: '团队认可你的技能，协作与持续学习会有成果。',
        wealth: '专业合作或技能投资有助于增加长期价值。',
        growth: '接受反馈并反复练习，让天赋变成可靠能力。',
      },
      reversed: {
        keywords: ['合作不良', '低质量', '缺乏认可'],
        general: '分工混乱或各自为政，使成果达不到标准。',
        love: '只有一方努力建设，关系缺少共同参与。',
        career: '团队沟通差、技能不足或劳动未获尊重。',
        wealth: '不专业的合作可能造成成本浪费，应重新审查。',
        growth: '放下自以为是，找到真正需要补强的基本功。',
      },
    },
  },
  {
    id: 'pentacles-four',
    number: 4,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'four',
    nameZh: '星币四',
    nameEn: 'Four of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Four.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['守成', '控制', '安全感'],
        general: '保护已有资源有其必要，但抓得过紧会阻止流动。',
        love: '害怕失去导致占有或保留，安全感需要通过信任建立。',
        career: '稳定职位与资源受到重视，创新空间可能较小。',
        wealth: '储蓄与保守管理有效，也要避免因恐惧拒绝合理使用。',
        growth: '观察自己紧抓什么，并理解背后的不安全感。',
      },
      reversed: {
        keywords: ['放手', '挥霍', '控制松动'],
        general: '你开始释放执着，或资源因缺乏控制而流失。',
        love: '愿意放下占有欲能改善亲密，失控则可能忽视承诺。',
        career: '旧职位或权力正在松动，需要适应新的资源分配。',
        wealth: '储蓄纪律下降或开始摆脱过度吝啬，保持适度。',
        growth: '让安全来自内在能力，而不是对外物的绝对控制。',
      },
    },
  },
  {
    id: 'pentacles-five',
    number: 5,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'five',
    nameZh: '星币五',
    nameEn: 'Five of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Five.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['匮乏', '困难', '被排除'],
        general: '现实压力带来孤立感，但可用的援助可能就在附近。',
        love: '经济或健康压力考验关系，彼此扶持胜过独自承受。',
        career: '失业、收入下降或缺乏支持，需要主动寻找资源。',
        wealth: '财务紧张应优先基本需求，并及时申请可靠帮助。',
        growth: '困境不等于个人失败，允许自己接收援手。',
      },
      reversed: {
        keywords: ['复苏', '获得帮助', '走出匮乏'],
        general: '最困难阶段开始过去，支持与现实改善逐渐出现。',
        love: '共同渡过低谷后关系有机会恢复温度和信任。',
        career: '工作机会或支援回归，重建过程需要耐心。',
        wealth: '现金流开始好转，持续修复储备并避免旧习惯。',
        growth: '从匮乏身份中走出，看见自己已经拥有的能力。',
      },
    },
  },
  {
    id: 'pentacles-six',
    number: 6,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'six',
    nameZh: '星币六',
    nameEn: 'Six of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Six.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['给予', '接受', '资源平衡'],
        general: '资源在公平交换中流动，慷慨与尊严可以同时存在。',
        love: '双方付出较为平衡，也愿意在需要时互相扶持。',
        career: '导师、奖金或资源支持出现，记得回馈团队。',
        wealth: '可获得援助或有能力帮助别人，但应明确边界。',
        growth: '练习既能大方给予，也能不羞耻地接受。',
      },
      reversed: {
        keywords: ['附带条件', '债务失衡', '单向付出'],
        general: '给予背后藏有控制，或资源交换明显不公平。',
        love: '一方用金钱或照顾换取服从，关系需要重设平等。',
        career: '承诺的报酬或支持不足，警惕被低估和利用。',
        wealth: '债务、借贷或慈善安排缺乏边界，应核对条件。',
        growth: '不以过度给予证明价值，也不把接受变成依赖。',
      },
    },
  },
  {
    id: 'pentacles-seven',
    number: 7,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'seven',
    nameZh: '星币七',
    nameEn: 'Seven of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Seven.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['耐心评估', '长期投入', '等待收成'],
        general: '成果正在生长，适合复盘投入并耐心等待成熟。',
        love: '关系需要时间培育，可共同评估长期投入是否值得。',
        career: '长期项目已有进展，调整方法比匆忙放弃更好。',
        wealth: '投资处于累积期，检视回报但避免短视。',
        growth: '尊重成长周期，以持续行动代替即时证明。',
      },
      reversed: {
        keywords: ['回报不足', '急躁', '无效投入'],
        general: '付出与成果不成比例，需要判断继续还是止损。',
        love: '长期努力没有回应，关系价值需要重新评估。',
        career: '项目迟迟无成果，可能方向错误或执行不持续。',
        wealth: '投资表现不佳，不要因沉没成本继续追加。',
        growth: '放下必须马上结果的焦虑，也诚实停止无效坚持。',
      },
    },
  },
  {
    id: 'pentacles-eight',
    number: 8,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'eight',
    nameZh: '星币八',
    nameEn: 'Eight of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Eight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['勤练', '专注', '精进'],
        general: '专注重复与细节正在提升技艺，稳定努力会被看见。',
        love: '愿意学习如何相处并落实小事，关系因此变得可靠。',
        career: '技能训练、认证与认真工作带来专业成长。',
        wealth: '凭手艺和纪律增加收入，复利来自长期积累。',
        growth: '接受熟练需要重复，把耐心放进每天的实践。',
      },
      reversed: {
        keywords: ['敷衍', '完美主义', '技能停滞'],
        general: '重复劳动失去专注，或过度追求细节阻碍完成。',
        love: '机械付出却缺少情感在场，需要改变相处方式。',
        career: '工作品质下降或技能跟不上，应重建学习计划。',
        wealth: '急于赚钱忽略专业基础，长期回报因此受限。',
        growth: '分辨精进与苛求，选择可持续而真实的练习。',
      },
    },
  },
  {
    id: 'pentacles-nine',
    number: 9,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'nine',
    nameZh: '星币九',
    nameEn: 'Nine of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Nine.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['独立', '成果享受', '自给自足'],
        general: '长期努力带来从容与自主，可以安心享受自己的成果。',
        love: '保持独立的同时开放亲密，不因寂寞降低标准。',
        career: '专业积累获得自由与认可，适合独立负责。',
        wealth: '财务较为稳健，可享受品质并维护长期资产。',
        growth: '欣赏自己建立的生活，让独处成为丰盛而非隔绝。',
      },
      reversed: {
        keywords: ['依赖', '表面富足', '自我价值不足'],
        general: '外在体面可能建立在透支或他人支持之上。',
        love: '过度独立拒绝连接，或因依赖失去自我。',
        career: '成果看似漂亮却缺少稳定基础，应补足真实能力。',
        wealth: '奢侈开销或收入依赖造成隐患，重新核对净资产。',
        growth: '不再用物质和完美生活证明自己值得被爱。',
      },
    },
  },
  {
    id: 'pentacles-ten',
    number: 10,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'ten',
    nameZh: '星币十',
    nameEn: 'Ten of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Ten.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['传承', '长期稳定', '家族资源'],
        general: '多年积累形成稳定结构，成果可以惠及更长远未来。',
        love: '关系重视家庭与长期承诺，适合建设共同生活。',
        career: '成熟组织、家业或长期事业带来可靠位置。',
        wealth: '资产、房产或传承规划有利，应兼顾下一代。',
        growth: '理解自己从何而来，并有意识地留下健康传承。',
      },
      reversed: {
        keywords: ['家族冲突', '基础不稳', '短视'],
        general: '长期结构出现裂缝，家族期待或旧制度带来压力。',
        love: '家庭价值冲突干扰伴侣关系，需要建立自己的规则。',
        career: '组织传统阻碍发展，或家族事业权责不清。',
        wealth: '遗产、房产或长期资产可能有争议与隐患。',
        growth: '结束代际重复的模式，不让传承变成束缚。',
      },
    },
  },
  {
    id: 'pentacles-page',
    number: 11,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'page',
    nameZh: '星币侍从',
    nameEn: 'Page of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Page.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['学习机会', '务实开始', '求知'],
        general: '一个可落实的学习或工作机会值得认真培养。',
        love: '以踏实而略显青涩的方式靠近，稳定行动建立信任。',
        career: '适合进修、实习或启动新技能，态度比资历重要。',
        wealth: '开始学习预算与投资，小额积累会形成基础。',
        growth: '把好奇心落到计划，享受从零掌握一件事。',
      },
      reversed: {
        keywords: ['拖延', '缺乏规划', '学习受阻'],
        general: '目标停在纸上，现实纪律不足使机会流失。',
        love: '承诺缺少行动或只顾现实利益，关系难以成长。',
        career: '学习不专心、准备不足，需重建基本工作习惯。',
        wealth: '忽视财务知识或追求快速收益，容易犯低级错误。',
        growth: '停止等待完美动机，用具体日程培养可靠性。',
      },
    },
  },
  {
    id: 'pentacles-knight',
    number: 12,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'knight',
    nameZh: '星币骑士',
    nameEn: 'Knight of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Knight.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['可靠', '勤勉', '稳步推进'],
        general: '缓慢而稳定的行动最可信，坚持流程会抵达目标。',
        love: '感情表达朴实但可靠，承诺通过日常行动兑现。',
        career: '认真执行和责任感带来稳定进展与信任。',
        wealth: '保守储蓄与长期投资适合当前，不必追逐快速回报。',
        growth: '把价值落实到习惯，让耐心成为真正力量。',
      },
      reversed: {
        keywords: ['停滞', '固执', '乏味'],
        general: '过度谨慎或机械重复使前进停滞，需要适度调整。',
        love: '关系安全却失去活力，或一方迟迟不愿向前。',
        career: '墨守流程而忽略目标，效率和动力都在下降。',
        wealth: '过分保守错失合理机会，也可能因懒散忽略账目。',
        growth: '纪律不等于僵化，给稳定生活加入有意识的变化。',
      },
    },
  },
  {
    id: 'pentacles-queen',
    number: 13,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'queen',
    nameZh: '星币王后',
    nameEn: 'Queen of Pentacles',
    image: new URL('../../tarot_img/Pentacles_Queen.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['滋养', '务实丰盛', '生活能力'],
        general: '温暖照料与现实能力结合，资源被安排得安稳而丰盛。',
        love: '以可靠关怀营造安全关系，也尊重身体与家庭需要。',
        career: '擅长协调人与资源，务实领导带来持续成果。',
        wealth: '精明管理家庭财务，懂得在储蓄与品质间平衡。',
        growth: '照顾身体和环境，让稳定日常支持内在成长。',
      },
      reversed: {
        keywords: ['自我忽视', '物质焦虑', '照顾失衡'],
        general: '忙于照顾现实和他人，自己的身心需求被遗忘。',
        love: '过度付出后积累怨气，或用物质代替情感陪伴。',
        career: '工作家庭失衡导致耗竭，需要重新分配责任。',
        wealth: '金钱焦虑引发控制或补偿消费，回到清楚预算。',
        growth: '先把关怀给自己，价值不取决于能照顾多少人。',
      },
    },
  },
  {
    id: 'pentacles-king',
    number: 14,
    arcana: 'minor',
    suit: 'pentacles',
    rank: 'king',
    nameZh: '星币国王',
    nameEn: 'King of Pentacles',
    image: new URL('../../tarot_img/Pentacles_King.jpg', import.meta.url).href,
    meanings: {
      upright: {
        keywords: ['稳健成功', '财富管理', '责任'],
        general: '经验与纪律创造长期稳定，资源被成熟地守护和运用。',
        love: '以忠诚、保护和实际承担表达长期承诺。',
        career: '商业判断稳健，适合管理资源并建立可持续事业。',
        wealth: '资产配置成熟，重视稳健回报与长期保障。',
        growth: '把成就转化为可靠支持，不让财富成为唯一身份。',
      },
      reversed: {
        keywords: ['贪婪', '顽固', '物质控制'],
        general: '对地位和金钱的执着压过伦理与真正安全。',
        love: '用资源控制伴侣或只看现实条件，亲密因此贫乏。',
        career: '保守专断、唯利是图使团队与事业失去信任。',
        wealth: '贪图收益或拒绝调整旧资产策略，风险正在累积。',
        growth: '重新定义成功，让价值不再只由拥有多少决定。',
      },
    },
  },
];

export const TAROT_CARDS: TarotCard[] = [
  ...majorArcana,
  ...wands,
  ...cups,
  ...swords,
  ...pentacles,
];
